"""add phone

Revision ID: 07df6a6cedad
Revises: f71e01ae725a
Create Date: 2022-08-17 10:35:20.285573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07df6a6cedad'
down_revision = 'f71e01ae725a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
